# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
      - uses: actions/checkout@v3
      
      - name: Copy PowerShell script to Windows Machine
        uses: appleboy/scp-action@main
        with:
          host: ${{ secrets.WINDOWS_MACHINE_HOST }} 
          username: ${{ secrets.WINDOWS_MACHINE_USERNAME }} 
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          source: "." 
          target: "C:/temp" 

