# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
defaults:
  run:
   shell: bash
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
      - uses: actions/checkout@v2
      
      
      - name: Install Azure PowerShell
        run: |
          pwsh -Command "Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser"
          pwsh -Command "Import-Module Az"

      - name: Copy PowerShell script to Azure VM
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          VM_PUBLIC_IP: "52.137.41.254"  # Replace with the public IP of your Azure Windows VM
        run: |
          $securePassword = ConvertTo-SecureString -AsPlainText -Force $env:AZURE_CLIENT_SECRET
          $credential = New-Object -TypeName PSCredential -ArgumentList $env:AZURE_CLIENT_ID, $securePassword

          az login --service-principal --username $env:AZURE_CLIENT_ID --password $env:AZURE_CLIENT_SECRET --tenant $env:AZURE_TENANT_ID
          az vm run-command invoke -g "testing" -n "testwinmachine" --command-id RunPowerShellScript --scripts "mkdir C:\temp"
          az vm run-command invoke -g "testing" -n "testwinmachine" --command-id RunPowerShellScript --scripts "Invoke-WebRequest -Uri 'https://github.com/teja2027/test_powershellscript_workflow/blob/main/testscript.ps1' -OutFile 'C:\temp\testscript.ps1'"
